/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "gpioChipTable.h"

static     netsnmp_handler_registration *my_handler = NULL;
static     netsnmp_table_array_callbacks cb;

const oid gpioChipTable_oid[] = { gpioChipTable_TABLE_OID };
const size_t gpioChipTable_oid_len = OID_LENGTH(gpioChipTable_oid);


#ifdef gpioChipTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int gpioChipTable_cmp( const void *lhs, const void *rhs );

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
gpioChipTable_cmp( const void *lhs, const void *rhs )
{
    gpioChipTable_context *context_l =
        (gpioChipTable_context *)lhs;
    gpioChipTable_context *context_r =
        (gpioChipTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "gpioChipTable_compare not implemented! Container order undefined\n" );
    return 0;
#endif
    
    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
gpioChipTable_context *
gpioChipTable_get( const char *name, int len )
{
    gpioChipTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);
    
    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "gpioChipTable_get not implemented!\n" );
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif


/************************************************************
 * Initializes the gpioChipTable module
 */
void
init_gpioChipTable(void)
{
    initialize_table_gpioChipTable();

    /*
     * TODO: perform any startup stuff here, such as
     * populating the table with initial data.
     *
     * gpioChipTable_context * new_row = create_row(index);
     * CONTAINER_INSERT(cb.container,new_row);
     */
}



/************************************************************
 *
 * Initialize the gpioChipTable table by defining its contents and how it's structured
 */
void
initialize_table_gpioChipTable(void)
{
    netsnmp_table_registration_info *table_info;

    if(my_handler) {
        snmp_log(LOG_ERR, "initialize_table_gpioChipTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("gpioChipTable",
                                             netsnmp_table_array_helper_handler,
                                             gpioChipTable_oid,
                                             gpioChipTable_oid_len,
                                             HANDLER_CAN_RONLY
                                             );
            
    if (!my_handler || !table_info) {
        snmp_log(LOG_ERR, "malloc failed in "
                 "initialize_table_gpioChipTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
        /** index: gpioChipIndex */
        netsnmp_table_helper_add_index(table_info, ASN_INTEGER);

    table_info->min_column = gpioChipTable_COL_MIN;
    table_info->max_column = gpioChipTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = gpioChipTable_get_value;
    cb.container = netsnmp_container_find("gpioChipTable_primary:"
                                          "gpioChipTable:"
                                          "table_container");
#ifdef gpioChipTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("gpioChipTable_custom:"
                                                       "gpioChipTable:"
                                                       "table_container"));
    cb.container->next->compare = gpioChipTable_cmp;
#endif
    DEBUGMSGTL(("initialize_table_gpioChipTable",
                "Registering table gpioChipTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * gpioChipTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int gpioChipTable_get_value(
            netsnmp_request_info *request,
            netsnmp_index *item,
            netsnmp_table_request_info *table_info )
{
    netsnmp_variable_list *var = request->requestvb;
    gpioChipTable_context *context = (gpioChipTable_context *)item;

    switch(table_info->colnum) {

        case COLUMN_GPIOCHIPINDEX:
            /** INTEGER32 = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->gpioChipIndex,
                         sizeof(context->gpioChipIndex) );
        break;
    
        case COLUMN_GPIOCHIPNAME:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->gpioChipName,
                         context->gpioChipName_len );
        break;
    
    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                 "gpioChipTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * gpioChipTable_get_by_idx
 */
const gpioChipTable_context *
gpioChipTable_get_by_idx(netsnmp_index * hdr)
{
    return (const gpioChipTable_context *)
        CONTAINER_FIND(cb.container, hdr );
}


