/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef GPIOCHIPTABLE_H
#define GPIOCHIPTABLE_H

#ifdef __cplusplus
extern "C" {
#endif

    
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index gpioChipIndex is internal */

typedef struct gpioChipTable_context_s {
    netsnmp_index index; /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
            long gpioChipIndex;

        /** DisplayString = ASN_OCTET_STR */
            unsigned char gpioChipName[255];
            long gpioChipName_len;


    /*
     * OR
     *
     * Keep a pointer to your data
     */
    void * data;

    /*
     *add anything else you want here
     */

} gpioChipTable_context;

/*************************************************************
 * function declarations
 */
void init_gpioChipTable(void);
void initialize_table_gpioChipTable(void);
const gpioChipTable_context * gpioChipTable_get_by_idx(netsnmp_index *);
const gpioChipTable_context * gpioChipTable_get_by_idx_rs(netsnmp_index *,
                                        int row_status);
int gpioChipTable_get_value(netsnmp_request_info *, netsnmp_index *, netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
extern const oid gpioChipTable_oid[];
extern const size_t gpioChipTable_oid_len;

#define gpioChipTable_TABLE_OID 1,3,6,1,4,1,5088,1
    
/*************************************************************
 * column number definitions for table gpioChipTable
 */
#define COLUMN_GPIOCHIPINDEX 1
#define COLUMN_GPIOCHIPNAME 2
#define gpioChipTable_COL_MIN 1
#define gpioChipTable_COL_MAX 2

/* comment out the following line if you don't want a custom sort  */
#define gpioChipTable_CUSTOM_SORT


#ifdef gpioChipTable_CUSTOM_SORT
gpioChipTable_context * gpioChipTable_get( const char *name, int len );
#endif

#ifdef __cplusplus
}
#endif

#endif /** GPIOCHIPTABLE_H */
